#:schema https://raw.githubusercontent.com/cloudflare/workers-sdk/main/packages/wrangler/config-schema.json
name = "chess-academy"
compatibility_date = "2024-05-02"

# This Tells Cloudflare to use the root directory for assets
[assets]
directory = "./"
